/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchedulerBuilderRouteImport } from './routes/scheduler-builder'
import { Route as ConfigBuilderRouteImport } from './routes/config-builder'
import { Route as BlueprintBuilderRouteImport } from './routes/blueprint-builder'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DockerComposeBuilderRouteImport } from './routes/docker/compose-builder'

const SchedulerBuilderRoute = SchedulerBuilderRouteImport.update({
  id: '/scheduler-builder',
  path: '/scheduler-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigBuilderRoute = ConfigBuilderRouteImport.update({
  id: '/config-builder',
  path: '/config-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintBuilderRoute = BlueprintBuilderRouteImport.update({
  id: '/blueprint-builder',
  path: '/blueprint-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DockerComposeBuilderRoute = DockerComposeBuilderRouteImport.update({
  id: '/docker/compose-builder',
  path: '/docker/compose-builder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blueprint-builder': typeof BlueprintBuilderRoute
  '/config-builder': typeof ConfigBuilderRoute
  '/scheduler-builder': typeof SchedulerBuilderRoute
  '/docker/compose-builder': typeof DockerComposeBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blueprint-builder': typeof BlueprintBuilderRoute
  '/config-builder': typeof ConfigBuilderRoute
  '/scheduler-builder': typeof SchedulerBuilderRoute
  '/docker/compose-builder': typeof DockerComposeBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blueprint-builder': typeof BlueprintBuilderRoute
  '/config-builder': typeof ConfigBuilderRoute
  '/scheduler-builder': typeof SchedulerBuilderRoute
  '/docker/compose-builder': typeof DockerComposeBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/blueprint-builder'
    | '/config-builder'
    | '/scheduler-builder'
    | '/docker/compose-builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/blueprint-builder'
    | '/config-builder'
    | '/scheduler-builder'
    | '/docker/compose-builder'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/blueprint-builder'
    | '/config-builder'
    | '/scheduler-builder'
    | '/docker/compose-builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BlueprintBuilderRoute: typeof BlueprintBuilderRoute
  ConfigBuilderRoute: typeof ConfigBuilderRoute
  SchedulerBuilderRoute: typeof SchedulerBuilderRoute
  DockerComposeBuilderRoute: typeof DockerComposeBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheduler-builder': {
      id: '/scheduler-builder'
      path: '/scheduler-builder'
      fullPath: '/scheduler-builder'
      preLoaderRoute: typeof SchedulerBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-builder': {
      id: '/config-builder'
      path: '/config-builder'
      fullPath: '/config-builder'
      preLoaderRoute: typeof ConfigBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint-builder': {
      id: '/blueprint-builder'
      path: '/blueprint-builder'
      fullPath: '/blueprint-builder'
      preLoaderRoute: typeof BlueprintBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docker/compose-builder': {
      id: '/docker/compose-builder'
      path: '/docker/compose-builder'
      fullPath: '/docker/compose-builder'
      preLoaderRoute: typeof DockerComposeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BlueprintBuilderRoute: BlueprintBuilderRoute,
  ConfigBuilderRoute: ConfigBuilderRoute,
  SchedulerBuilderRoute: SchedulerBuilderRoute,
  DockerComposeBuilderRoute: DockerComposeBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
